name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DATABASE: wca_development
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -u root -p 'password'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download, Unzip, and Import WCA Database Dump
        run: |
          DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD || 'password' }}
          
          echo "Downloading and unzipping database dump..."
          wget --quiet https://www.worldcubeassociation.org/wst/wca-developer-database-dump.zip
          unzip wca-developer-database-dump.zip
          
          echo "Importing data to database wca_development..."
          mysql --host=mysql --port=3306 --user=root --password="${DB_PASSWORD}" wca_development < wca-developer-database-dump.sql
          
          echo "Delete zip file..."
          rm wca-developer-database-dump.zip
          rm wca-developer-database-dump.sql
          df -h

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py

      - name: Copy _config
        run: cp _config.yml output/_config.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          keep_files: true
          enable_jekyll: true
          allow_empty_commit: true
